site_name: Blockchain
site_url: https://vikian050194.github.io/blockchain/
repo_url: https://github.com/vikian050194/blockchain/
nav:
    - Экзамен: exam.md
    - Задачки:
        - Список: tasks/index.md
        - Coin: tasks/coin.md
        - Storage: tasks/storage.md
        - Elections: tasks/elections.md
    - Занятия:
        - '0. Вводное':
            - Вопросики: 00/questions.md
            - Промышленная разработка: 00/development.md
            - Тестирование: 00/testing.md
            - Git: 00/git.md
            - OS: 00/os.md
            - Python: 00/python.md
            - IDE': 00/ide.md
        - '1. Что есть что':
            - Blockchain: 01/blockchain.md
            - Etherium: 01/etherium.md
            - Языки смарт-контрактов: 01/contract.md
            - Solidity: 01/solidity.md
            - Online IDE Remix: 01/remix.md
            - Online IDE ethfiddle: 01/ethfiddle.md
            - Контракт Storage: tasks/storage.md
            - Контракт Coin: tasks/coin.md
        - '2. Обернём в питона':
            - Accounts: 02/accounts.md
            - Gas и прочее: 02/gas.md
            - Web3 и провайдеры: 02/web3.md
            - Обёртка (пышка): 02/wrapper.md
            - Пример транзакции: 02/transaction.md
            - Домашка: 02/homework.md
        - '3. Гошная нода':
            - Протоколы: 03/protocol.md
            - TODO Клиенты Etherium сети: 03/client.md
            - Geth: 03/geth.md
            - Тестовая сеть: testnet.md
            - Пример транзакции: 03/transaction.md
            - Домашка: 03/homework.md
            # - Получение аккаунтов пира:
        - '4. Сеть':
            - TODO Syncmode: 04/sync.md
            - Компилятор solc: 04/solc.md
            - Контракт Storage: tasks/storage.md
            - Контракт Coin: tasks/coin.md
            - Домашка: 04/homework.md
        - '5. Тестирование':
            - TODO Тестирование: 05/testing.md
        - '6. Майнинг':
            - TODO Майнинг: 06/mining.md
theme:
    name: material
    locale: ru
    features:
    - navigation.tabs
    - navigation.instant
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
    - pymdownx.snippets:
        check_paths: true
    - toc:
        permalink: true
        baselevel: 3
        separator: "_"
